# tests/test_writer_agent.py
import pytest

from src.agents.writer_agent import WriterAgent

SUMMARY = """# AI/ML Daily Digest - Summary

**Total Articles:** 2

## LLM (1 articles)

Un modelo abierto de gran tamaño fue publicado.

---
"""


@pytest.mark.asyncio
async def test_writer_creates_newsletter(llm_completion, tmp_path):
    """Writes the newsletter (real LLM, mock fallback if it fails)."""
    summary_file = tmp_path / "summary.md"
    output_file = tmp_path / "out" / "newsletter.md"  # parent dir must be created
    summary_file.write_text(SUMMARY, encoding="utf-8")

    result = await WriterAgent().execute(str(summary_file), str(output_file))

    assert result["success"] is True
    text = output_file.read_text(encoding="utf-8")
    # Structure comes from the agent, so it holds for real and mock LLM output
    assert text.startswith("# AI/ML Daily Newsletter - ")
    assert "Generated by AI Agent Pipeline" in text
    assert len(text.splitlines()) > 5
